# Generated by Django 3.1 on 2020-08-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageproc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
