# Generated by Django 3.1 on 2020-08-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageproc', '0002_images_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
